

NETWORK[:Ångermanälven] = [
        # Upstream plant: name, dischargedelay (h), utskovdelay, passagedelay (h), drybeddelay (h) (if -1, there is no such passage)
        Connection(:Linnvasselv), 
        Connection(:Blåsjön),            
        Connection(:Junsterforsen,     Upstream(:Blåsjön,        1,  1, -1, -1)), 
        Connection(:Gäddede,           Upstream(:Junsterforsen,  1,  1, -1, -1), Upstream(:Linnvasselv, 1,  1, -1, -1)), 
        Connection(:Bågede,            Upstream(:Gäddede,        1,  1, -1, -1)),                                      
        Connection(:Lövön,             Upstream(:Bågede,         1,  1, -1, -1)), 
        Connection(:Storfinnforsen,    Upstream(:Lövön,          0,  0, -1, -1)),                                       
        Connection(:Ramsele,           Upstream(:Storfinnforsen, 1,  1, -1, -1)),                                      
        Connection(:Edsele,            Upstream(:Ramsele,        1,  1, -1, -1)),                                    
        Connection(:Graninge), 
        Connection(:Ledinge,           Upstream(:Graninge,       1,  1, -1, -1)),                              
        Connection(:Forsse,            Upstream(:Ledinge,        1,  1, -1, -1), Upstream(:Edsele, 1,  1, -1, -1)),
        Connection(:Hjälta,            Upstream(:Forsse,         1,  1, -1, -1)),                              
        Connection(:Storsjouten),
        Connection(:Nåsjön),                                                                             
        Connection(:Bergvattnet,       Upstream(:Storsjouten,   -1,  1, -1, -1), Upstream(:Nåsjön, -1,  1, -1, -1)),
        Connection(:Borgasjön),
        Connection(:Dabbsjö,           Upstream(:Borgasjön,     -1,  1, -1, -1)),
        Connection(:Stora_raijan,      Upstream(:Dabbsjö,        1,  1, -1, -1)),
        Connection(:Korsselbränna,     Upstream(:Storsjouten,   -1,  1, -1, -1), Upstream(:Nåsjön, -1,  1, -1, -1), Upstream(:Bergvattnet, 1,  1, -1, -1), Upstream(:Stora_raijan, -1,  1, -1, -1)),
        Connection(:Tåsjö,             Upstream(:Korsselbränna,  1,  1, -1, -1), Upstream(:Stora_raijan, -1,  1, -1, -1)),
        Connection(:Klingerforsen),                                                                     
        Connection(:Hoting,            Upstream(:Tåsjö,          1,  1, -1, -1), Upstream(:Klingerforsen, 1,  1, -1, -1)),
        Connection(:Ormsjön),
        Connection(:Borgforsen,        Upstream(:Ormsjön,       -1,  1, -1, -1), Upstream(:Hoting, -1,  1, -1, -1)),
        Connection(:Bodum,             Upstream(:Borgforsen,     1,  1, -1, -1), Upstream(:Hoting, 1,  1, -1, -1)),
        Connection(:Fjällsjö,          Upstream(:Bodum,          1,  1, -1, -1)),
        Connection(:Sil,               Upstream(:Fjällsjö,       1,  1, -1, -1)),
        Connection(:Vängelsjön,        Upstream(:Storfinnforsen,-1,  2, -1, -1), Upstream(:Lövön,  -1, 4, -1, -1)),
        Connection(:Kilforsen,         Upstream(:Sil,            1,  1, -1, -1), Upstream(:Vängelsjön, -1, 1, -1, -1)),
        Connection(:Ransaren),
        Connection(:Stalon,            Upstream(:Ransaren,      -1,  0, -1, -1)),
        Connection(:Malgomaj,          Upstream(:Stalon,         0,  0, -1, -1)),
        Connection(:Vojmsjön),
        Connection(:Volgsjöfors,       Upstream(:Malgomaj,       1,  1, -1, -1), Upstream(:Vojmsjön,  -1,  1, -1, -1)),
        Connection(:Stenkulla,         Upstream(:Volgsjöfors,    0,  0, -1, -1)),
        Connection(:Åsele,             Upstream(:Stenkulla    ,  2,  2, -1, -1)),
        Connection(:Hällby,            Upstream(:Åsele,          3,  3, -1, -1)),
        Connection(:Gulsele,           Upstream(:Hällby,         1,  1, -1, -1)),
        Connection(:Degerforsen,       Upstream(:Gulsele,        1,  1, -1, -1)),
        Connection(:Edensforsen,       Upstream(:Degerforsen,    1,  1, -1, -1)),
        Connection(:Långbjörn,         Upstream(:Edensforsen,    1,  1, -1, -1)),
        Connection(:Lasele,            Upstream(:Långbjörn,      1,  1, -1, -1)),
        Connection(:Nämforsen,         Upstream(:Lasele,         1,  1, -1, -1), Upstream(:Kilforsen, 1,  1, -1, -1), Upstream(:Sil, -1,  3, -1, -1), Upstream(:Vängelsjön, -1,  4, -1, -1)),
        Connection(:Moforsen,          Upstream(:Nämforsen,      0,  0, -1, -1)),
        Connection(:Forsmo,            Upstream(:Moforsen,       1,  1, -1, -1)),
        Connection(:Sollefteå,         Upstream(:Hjälta,         1,  1, -1, -1), Upstream(:Forsmo, 1,  1, -1, -1)),
        Connection(:Hav,               Upstream(:Sollefteå,      0,  0, -1, -1))
    ]