

NETWORK[:Indalsälven] = [
        # Upstream plant: name, dischargedelay (h), utskovdelay, passagedelay (h), drybeddelay (h) (if -1, there is no such passage)
        Connection(:Lillå),            
        Connection(:Strömbacka,        Upstream(:Lillå,           0, 0, -1, -1)), 
        Connection(:Billsta,           Upstream(:Strömbacka,      1, 1, -1, -1)), 
        Connection(:Sällsjö),           
        Connection(:Duved),             
        Connection(:Slagsån),           
        Connection(:Anjan),             
        Connection(:Torrön),            
        Connection(:Juveln,            Upstream(:Torrön,           1, 1, -1, -1)), 
        Connection(:Järpströmmen,      Upstream(:Juveln,           3, 3, -1, -1), Upstream(:Anjan, 2, 2, -1, -1)), 
        Connection(:Mörsil,            Upstream(:Järpströmmen,     2, 2, -1, -1), Upstream(:Slagsån, 1, 1, -1, -1), Upstream(:Duved,  3, 3, -1, -1)),
        Connection(:Ockesjön,          Upstream(:Mörsil,           1, 1, -1, -1), Upstream(:Sällsjö, 0, 0, -1, -1)), 
        Connection(:Alsensjön),         
        Connection(:Hissmofors,        Upstream(:Alsensjön,       -1,  1, -1, -1), Upstream(:Ockesjön,-1, 0, -1, -1), Upstream(:Billsta, 0, 0, -1, -1)),           
        Connection(:Kattstrupeforsen,  Upstream(:Hissmofors,       0,  0, -1, -1)), 
        Connection(:Granboforsen,      Upstream(:Kattstrupeforsen, 0,  0, -1, -1)),
        Connection(:Långså),            
        Connection(:Oldå),              
        Connection(:Rönnöfors,         Upstream(:Oldå,             2,  2, -1, -1), Upstream(:Långså, 2,  2, -1, -1)),
        Connection(:Landösjön,         Upstream(:Rönnöfors,        6,  6, -1, -1)),
        Connection(:Stensjöfallet),     
        Connection(:Kvarnfallet,       Upstream(:Stensjöfallet,    0,  0, -1, -1)),                                    
        Connection(:Lövhöjden),         
        Connection(:Ålviken,           Upstream(:Lövhöjden,        0,  0, -1, -1)),
        Connection(:Näsaforsen,        Upstream(:Ålviken,          0,  0, -1, -1), Upstream(:Kvarnfallet, 3,  3, -1, -1)), 
        Connection(:Högfors,           Upstream(:Näsaforsen,       3,  3, -1, -1)), 
        Connection(:Midskog,           Upstream(:Högfors,          2,  2, -1, -1), Upstream(:Landösjön, -1,  3, -1, -1), Upstream(:Granboforsen, 2,  2, -1, -1)),
        Connection(:Näverede,          Upstream(:Midskog,          0,  0, -1, -1)),
        Connection(:Stugun,            Upstream(:Näverede,         1,  1, -1, -1)),
        Connection(:Krångede,          Upstream(:Stugun,           2,  2, -1, -1)), 
        Connection(:Gammelänge,        Upstream(:Krångede,         0,  0, -1, -1)), 
        Connection(:Hammarforsen,      Upstream(:Gammelänge,       1,  1, -1, -1)),
        Connection(:Svarthålsforsen,   Upstream(:Hammarforsen,     1,  1, -1, -1)),
        Connection(:Stadsforsen,       Upstream(:Svarthålsforsen,  0,  0, -1, -1)),
        Connection(:Hölleforsen,       Upstream(:Stadsforsen,      0,  0, -1, -1)),
        Connection(:Järkvissle,        Upstream(:Hölleforsen,      1,  1, -1, -1)),
        Connection(:Sillre),            
        Connection(:Bergeforsen,       Upstream(:Sillre,           0,  0, -1, -1), Upstream(:Järkvissle, 2,  2, -1, -1)),
        Connection(:Hav,               Upstream(:Bergeforsen,      0,  0, -1, -1))
        ]