
NETWORK[:Dalälven] = [
        # Upstream plant: name, dischargedelay (h), utskovdelay, passagedelay (h), drybeddelay (h) (if -1, there is no such passage)
        Connection(:Horrmund), 
        Connection(:Lima,            Upstream(:Horrmund,      10, 10, -1, -1)), 
        Connection(:Hummelforsen,    Upstream(:Lima,          11, 11, -1, -1)),             
        Connection(:Eldforsen,       Upstream(:Hummelforsen,   0,  0, -1, -1)), 
        Connection(:Öjesjön),        
        Connection(:Johannisholm,    Upstream(:Öjesjön,       -1,  5, -1, -1)),
        Connection(:Gävunda,         Upstream(:Johannisholm,   3,  3, -1, -1)), 
        Connection(:Snesen),         
        Connection(:Mockfjärd,       Upstream(:Snesen,        -1,  5, -1, -1), Upstream(:Eldforsen, 1,  1, -1, -1), Upstream(:Gävunda, 4,  4, -1, -1)),                                     
        Connection(:Lindbyn,         Upstream(:Mockfjärd,      0,  0, -1, -1)),
        Connection(:Trängslet),    
        Connection(:Åsen,            Upstream(:Trängslet,      2,  2, -1, -1)),
        Connection(:Väsa,            Upstream(:Åsen,           4,  4, -1, -1)),
        Connection(:Blyberg,         Upstream(:Väsa,           0,  0, -1, -1)),
        Connection(:Spjutmo,         Upstream(:Blyberg,        2,  2, -1, -1)),
        Connection(:Vässinkoski),    
        Connection(:Noppikoski,      Upstream(:Vässinkoski,    2,  2, -1, -1)),
        Connection(:Furudal,         Upstream(:Noppikoski,     0,  0, -1, -1)), 
        Connection(:Skattungen,      Upstream(:Furudal,        4,  4, -1, -1)),
        Connection(:Unnån,           Upstream(:Skattungen,     0,  0, -1, -1)),
        Connection(:Hansjö,          Upstream(:Unnån,          0,  0, -1, -1)),
        Connection(:Gråda,           Upstream(:Spjutmo,       10, 10, -1, -1), Upstream(:Hansjö, 10, 10, -1, -1)),
        Connection(:Forshuvud,       Upstream(:Gråda,          3,  3, -1, -1), Upstream(:Lindbyn, 0,  0, -1, -1)),
        Connection(:Kvarnsveden,     Upstream(:Forshuvud,      0,  0, -1, -1)),
        Connection(:Bullerforsen,    Upstream(:Kvarnsveden,    0,  0, -1, -1)),
        Connection(:Domnarvet,       Upstream(:Bullerforsen,   0,  0, -1, -1)),
        Connection(:Ljugaren),       
        Connection(:Dalstuga),                                             
        Connection(:Tänger,          Upstream(:Dalstuga,         4,  4, -1, -1)),
        Connection(:Borgärdet,       Upstream(:Ljugaren,        -1,  7, -1, -1), Upstream(:Tänger, 6, 6, -1, -1)),
        Connection(:Runn,            Upstream(:Borgärdet,        8,  8, -1, -1)), 
        Connection(:Långhag,         Upstream(:Runn,            -1,  0, -1, -1), Upstream(:Domnarvet, 0, 0, -1, -1)),
        Connection(:Skedvi,          Upstream(:Långhag,          0,  0, -1, -1)),
        Connection(:Avestaforsen,    Upstream(:Skedvi,           7,  7, -1, -1)),
        Connection(:Avesta_Lillfors, Upstream(:Avestaforsen,     0,  0, -1, -1)),
        Connection(:Näs,             Upstream(:Avesta_Lillfors, 12, 12, -1, -1)),
        Connection(:Söderfors,       Upstream(:Näs,             48, 48, -1, -1)), 
        Connection(:Untra,           Upstream(:Söderfors,        1,  1, -1, -1)),
        Connection(:Lanforsen,       Upstream(:Untra,            2,  2, -1, -1)),
        Connection(:Älvkarleby,      Upstream(:Lanforsen,        0,  0, -1, -1)),
        Connection(:Hav,             Upstream(:Älvkarleby,       0,  0, -1, -1))
    ]